### ISSUE TITLE
Mobile Design - Updates

### ISSUE THREAD

**Issue by Andresmaldonadonormelli** [ultra-sound-music/ultra-sound-music#56]
- 55px Header hight (Mobile+Tablet)
- 15px Left / Right side margins
- Larger Hero image
- 14px Bodycopy text size. 
- Update Info box
- Center align copy in sections "Traits" "About" and "Crew"
- Space out the traits section a bit

<img width="821" alt="Screen Shot 2022-02-19 at 12 05 57 PM" src="https://user-images.githubusercontent.com/71088838/154811341-8d09cc87-d32a-495a-b20c-63c64d18e94a.png">
 
<img width="210" alt="Screen Shot 2022-02-19 at 1 05 02 PM" src="https://user-images.githubusercontent.com/71088838/154813283-2178b4d5-97f0-45be-a481-4ddc699c141c.png">

**Comment by gxxcastillo** [comment]
Done, except for the header being resized to 55px on mobile.  Gonna close this out for now will ping you on Discord for a new image file.
