### ISSUE TITLE
Copy Updates Site

### ISSUE THREAD

**Issue by Andresmaldonadonormelli** [ultra-sound-music/ultra-sound-music#57]
- Updated Hero section copy

- Updated Traits section copy

- Update Andres Twitter (https://twitter.com/0xChillDirector)

- Update Subhead on "Blockchain Musicians" should read "What are Jambots?"

<img width="573" alt="Screen Shot 2022-02-19 at 12 53 06 PM" src="https://user-images.githubusercontent.com/71088838/154812877-d5349e50-812d-42b8-ba96-c198d0c32be3.png">

<img width="494" alt="Screen Shot 2022-02-19 at 12 54 35 PM" src="https://user-images.githubusercontent.com/71088838/154812908-7d1dc231-234a-4708-a5db-7044f32f96b3.png">

**Comment by gxxcastillo** [comment]
> Update Subhead on "Blockchain Musicians" should read "What are Jambots?"

Just to confirm, this is the desired copy?

<img width="665" alt="Screen Shot 2022-02-24 at 8 37 15 AM" src="https://user-images.githubusercontent.com/530233/155567587-54c0f036-6efe-4a94-b46c-047246b07594.png">

**Comment by gxxcastillo** [comment]
@Andresmaldonadonormelli , fyi, it isn't true that the metadata and traits cannot be updated.  We can and will be updating some of these at different points in time
