### ISSUE TITLE
Mobile Right Side - Issue

### ISSUE THREAD

**Issue by Andresmaldonadonormelli** [ultra-sound-music/ultra-sound-music#59]
On mobile if I zoom out and in of the site, there is a right side margin that get's white and then stays there. 
Not sure 

![IMG_6235](https://user-images.githubusercontent.com/71088838/154857742-f1872554-83d6-4abc-b38b-bb0c0d447876.PNG)

**Comment by gxxcastillo** [comment]
hmmm...that's really weird.  What device are you on?

**Comment by gxxcastillo** [comment]
nm, Its fixed now. I had forgotten to resize the logo down from 420px when the screen is narrower than the logo.
